version: '2'

services:
  backend-1:
    image: datastax/dse-server:${DSETAG}
    networks:
      - backend-studio
    ports:
      - 9042:9042
      - 9044:9044
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - SEEDS=backend-1
      - CLUSTER_NAME=dse${DSETAG}-cluster
      - DC=datacenter1
      - RACK=rack1
      - DS_LICENSE=accept
  backend-2:
    image: datastax/dse-server:${DSETAG}
    networks:
      - backend-studio
    mem_limit: 2G
    depends_on:
      - backend-1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - SEEDS=backend-1
      - CLUSTER_NAME=dse${DSETAG}-cluster
      - DC=datacenter1
      - RACK=rack1
      - DS_LICENSE=accept
  backend-3:
    image: datastax/dse-server:${DSETAG}
    networks:
      - backend-studio
    mem_limit: 2G
    depends_on:
      - backend-2
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - SEEDS=backend-1
      - CLUSTER_NAME=dse${DSETAG}-cluster
      - DC=datacenter1
      - DS_LICENSE=accept
  studio:
    image: datastax/dse-studio:${STUDIOTAG}
    depends_on: 
      - backend-1
    environment:
      - DS_LICENSE=accept
    networks:
      - backend-studio
    ports:
      - 9091:9091
networks:
  backend-studio:
